using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using gift_of_the_givers.Data;
using gift_of_the_givers.Models;
using gift_of_the_givers.Services;

namespace gift_of_the_givers.Pages.Donation;

public class CertificateModel : PageModel
{
    private readonly ApplicationDbContext _db;
    private readonly AzureFunctionsClient _functions;

    public CertificateModel(ApplicationDbContext db, AzureFunctionsClient functions)
    {
        _db = db;
        _functions = functions;
    }

    public global::gift_of_the_givers.Models.Donation? Donation { get; private set; }

    // Certificate generated by the GenerateTaxCertificate Azure Function (null when the function is offline).
    public FunctionTaxCertificate? FunctionCertificate { get; private set; }

    // What the donation pays for in relief items, e.g. "2 food parcels for families".
    public IReadOnlyList<ImpactLine> ImpactLines { get; private set; } = Array.Empty<ImpactLine>();

    public string CertificateNumber => FunctionCertificate?.CertificateNumber
        ?? (Donation is null ? string.Empty : $"GOTG-{Donation.Id:000000}");

    public string DonorDisplayName => Donation is null
        ? string.Empty
        : (Donation.IsAnonymous || string.IsNullOrWhiteSpace(Donation.DonorName) ? "Anonymous Donor" : Donation.DonorName);

    // Loads the saved donation and asks the Azure Function to generate its dummy tax certificate.
    public async Task<IActionResult> OnGetAsync(int id)
    {
        Donation = await _db.GetDonationByIdAsync(id);
        if (Donation is null)
        {
            return NotFound();
        }

        FunctionCertificate = await _functions.GenerateTaxCertificateAsync(Donation);
        ImpactLines = DonationImpactCalculator.Calculate(Donation.Amount, Donation.Currency, Donation.Frequency);

        return Page();
    }

    // Creates a downloadable PDF version of the same placeholder certificate so the user can keep a copy.
    public async Task<IActionResult> OnGetPdfAsync(int id)
    {
        var donation = await _db.GetDonationByIdAsync(id);
        if (donation is null)
        {
            return NotFound();
        }

        var donorDisplayName = donation.IsAnonymous || string.IsNullOrWhiteSpace(donation.DonorName)
            ? "Anonymous Donor"
            : donation.DonorName;

        var functionCertificate = await _functions.GenerateTaxCertificateAsync(donation);

        var pdfBytes = DonationCertificatePdfBuilder.Build(
            donation,
            functionCertificate?.CertificateNumber ?? $"GOTG-{donation.Id:000000}",
            donorDisplayName,
            DateTime.UtcNow);

        return File(pdfBytes, "application/pdf", $"tax-certificate-{donation.Id:000000}.pdf");
    }
}
